$('.active-menu').click(function(){
	$('.menu').toggleClass('d-n');
});
$('.close-menu').click(function(){
	$('.menu').toggleClass('d-n');
});
$('.active-carta-blog').click(function(){
	$('.carta-lbog').toggleClass('d-n');
});